name: Python CI

on:
  push:
  pull_request:

env:
  PYTHON_VERSION: "3.11"

jobs:
  lint-and-basic-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync --dev

      - name: Lint with ruff
        run: |
          uv run ruff check
          uv run ruff format --check

      - name: Test CLI help commands
        run: |
          uv run docling-japanese-books --help
          uv run docling-japanese-books download --help
          uv run docling-japanese-books process --help
          uv run docling-japanese-books search --help
